# river bridge report
CREATE_BRIDGE_REPORT: true
scenario = ['2019', '2050']
county = ['Hamilton','Walker'] # four counties 'Hamilton','Walker','Dade','Catoosa'

# scenario impact report
CREATE_IMPACT_REPORT: false
scenario = ['2019', '2050']
link_query = 'link_id.csv'
# area_query = 'FUNCCLASS<=7'

# project evaluation report
CREATE_EVALUATION_REPORT: false
scenario = ['2019', '2050']
link_query = 'cummings_hwy.csv'

# map automation
CREATE_MAP_OUTPUT: false
scenario = ['2019']

