
path: C:\Current\yerra\Chattanooga\_data_for_repo\model outputs

alternatives: base year

taz_dist_xref: county_districts_chattanooga.csv

excludeChildren5: True
runWrkSchLocationChoice: True
runVehAvailability: True
runDayPattern: True
runTourDestination: True
runTourMode: True
runTourTOD: True
runTripDestination: True
runTripMode: True
runTripTOD: True
