
path: C:\Users\USYS671257\OneDrive - WSP O365\21_31000110.002_Chattanooga TPO Model\model outputs

alternatives: 2025

taz_dist_xref: county_districts_chattanooga.csv

excludeChildren5: True
runWrkSchLocationChoice: True
runVehAvailability: True
runDayPattern: True
runTourDestination: True
runTourMode: True
runTourTOD: True
runTripDestination: True
runTripMode: True
runTripTOD: True
